<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\API\Courier;

use Tracking\Model\Base\Base;

class DetectCourierRequest extends Base
{
    /**
     * @var TrackingDetectCourierRequest Detect courier request
     */
    public $tracking;
}
