<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\API\Courier;

use Tracking\Model\Base\Base;

class DetectCourierRequest extends Base
{
    /**
     * @var string Tracking number of a shipment.
     */
    public $tracking_number;
    /**
     * @var array[] If not specified, Aftership will automatically detect the courier based on the tracking number format and your . Use array to input a list of couriers for auto detect. Cannot be used with slug_group at the same time.
     */
    public $slug;
    /**
     * @var string The postal code of receiver's address. Required by some couriers. Refer to  for more details
     */
    public $tracking_postal_code;
    /**
     * @var string Shipping date in `YYYYMMDD` format. Required by some couriers. Refer to  for more details
     */
    public $tracking_ship_date;
    /**
     * @var string Account number of the shipper for a specific courier. Required by some couriers. Refer to  for more details
     */
    public $tracking_account_number;
    /**
     * @var string Key of the shipment for a specific courier. Required by some couriers. Refer to  for more details
     */
    public $tracking_key;
    /**
     * @var string Origin Country/Region of the shipment for a specific courier. Required by some couriers.
     */
    public $tracking_origin_country;
    /**
     * @var string Destination Country/Region of the shipment for a specific courier. Required by some couriers. Refer to  for more details
     */
    public $tracking_destination_country;
    /**
     * @var string State of the destination shipping address of the shipment. Required by some couriers.
     */
    public $tracking_state;
    /**
     * @var string|null|\Tracking\Model\SlugGroupV1 Slug group is a group of slugs which belong to same courier. For example, when you inpit "fedex-group" as slug_group, AfterShip will detect the tracking with "fedex-uk", "fedex-fims", and other slugs which belong to "fedex". It cannot be used with slug at the same time. (
     */
    public $slug_group;
    /**
     * @var string Enter .
     */
    public $origin_country_iso3;
    /**
     * @var string Enter .
     */
    public $destination_country_iso3;
}
