<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\API\Courier;

use Tracking\Model\Base\Base;

class GetUserCouriersResponse extends Base
{
    /**
     * @var int Total count of courier objects
     */
    public $total;
    /**
     * @var \Tracking\Model\Courier[] Array of  object.
     */
    public $couriers;
}
