<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class AdditionalFieldsV1
{
    const TRACKING_ACCOUNT_NUMBER = "tracking_account_number";
    const TRACKING_POSTAL_CODE = "tracking_postal_code";
    const TRACKING_SHIP_DATE = "tracking_ship_date";
    const TRACKING_KEY = "tracking_key";
    const TRACKING_ORIGIN_COUNTRY = "tracking_origin_country";
    const TRACKING_DESTINATION_COUNTRY = "tracking_destination_country";
    const TRACKING_STATE = "tracking_state";
}
