<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class AdditionalFields
{
    const TRACKING_ACCOUNT_NUMBER = "tracking_account_number";
    const DESTINATION_POSTAL_CODE = "destination_postal_code";
    const DESTINATION_STATE = "destination_state";
    const TRACKING_KEY = "tracking_key";
    const ORIGIN_COUNTRY_REGION = "origin_country_region";
    const DESTINATION_COUNTRY_REGION = "destination_country_region";
    const TRACKING_SHIP_DATE = "tracking_ship_date";
    const CUSTOMERS_X_PHONE_NUMBER = "customers[x].phone_number";
}
