<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

enum AdditionalFields: string
{
    case TRACKING_ACCOUNT_NUMBER = "tracking_account_number";
    case DESTINATION_POSTAL_CODE = "destination_postal_code";
    case DESTINATION_STATE = "destination_state";
    case TRACKING_KEY = "tracking_key";
    case ORIGIN_COUNTRY_REGION = "origin_country_region";
    case DESTINATION_COUNTRY_REGION = "destination_country_region";
    case TRACKING_SHIP_DATE = "tracking_ship_date";
}
