<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class CheckpointEventsReason extends Base
{
    /**
     * @var string|null The code of the reason.
     */
    public $code;
}
