<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class CheckpointEvents extends Base
{
    /**
     * @var string|null Represents the event code.
     */
    public $code;

    /**
     * @var \Tracking\Model\CheckpointEventsReason|null Describes the specific reason that led to the event.
     */
    public $reason;
}
