<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class CoordinateCheckpoint extends Base
{
    /**
     * @var int|float Represents the latitude.
     */
    public $latitude;
    /**
     * @var int|float Represents the longitude.
     */
    public $longitude;
}
