<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class CourierConnectionResponseForGetCourierConnections extends Base
{
    /**
     * @var \Tracking\Model\Meta Meta data
     */
    public $meta;
    /**
     * @var DataCourierConnectionResponseForGetCourierConnections
     */
    public $data;
}
