<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class Courier extends Base
{
    /**
     * @var string Unique code of courier. Get the slugs from .
     */
    public $slug;
    /**
     * @var string Name of courier
     */
    public $name;
    /**
     * @var string|null Contact phone number of courier
     */
    public $phone;
    /**
     * @var string|null Other name of courier
     */
    public $other_name;
    /**
     * @var string Website link of courier
     */
    public $web_url;
    /**
     * @var array[] The extra fields need for tracking, such as `tracking_account_number`, `tracking_postal_code`, `tracking_ship_date`, `tracking_key`, `tracking_destination_country`
     */
    public $required_fields;
    /**
     * @var array[] The extra fields which are optional for tracking. Basically it's the same as required_fields, but the difference is that only some of the tracking numbers require these fields.
     */
    public $optional_fields;
    /**
     * @var string Default language of tracking results
     */
    public $default_language;
    /**
     * @var array[] Other supported languages
     */
    public $support_languages;
    /**
     * @var array[] Country/Region code (ISO Alpha-3) where the courier provides service
     */
    public $service_from_country_iso3;
}
