<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class CourierConnection extends Base
{
    /**
     * @var string The courier connection ID is a special set of numbers generated by AfterShip to define each user-created connection.
     */
    public $id;
    /**
     * @var string Unique courier code. Get courier codes .
     */
    public $courier_slug;
    /**
     * @var array|null It refers to the authentication details required for each specific carrier details required for each specific carrier (such as API keys, username, password, etc.) that the user must provide to establish a carrier connection. The content varies by carrier.
     */
    public $credentials;
    /**
     * @var string The date and time the courier connection was created. It uses the format YYYY-MM-DDTHH:mm:ssZ for the timezone GMT +0.
     */
    public $created_at;
    /**
     * @var string The date and time the courier connection was updated. It uses the format YYYY-MM-DDTHH:mm:ssZ for the timezone GMT +0.
     */
    public $updated_at;
}
