<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class CreateTrackingRequestLastMile extends Base
{
    /**
     * @var string|null The tracking number of the last-mile carrier.
     * @required
     */
    public $tracking_number;

    /**
     * @var string|null The unique code of the carrier responsible for the last-mile of the shipment.  Find all the courier slugs .
     */
    public $slug;
}
