<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

enum CreateTrackingRequestDeliveryType: string
{
    case PICKUP_AT_STORE = "pickup_at_store";
    case DOOR_TO_DOOR = "door_to_door";
    case PICKUP_AT_COURIER = "pickup_at_courier";
}
