<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class DataTrackingDeleteResponseV1 extends Base
{
    /**
     * @var \Tracking\Model\PartialDeleteTracking Partial tracking model
     */
    public $tracking;
}
