<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class DataNotificationResponseV1 extends Base
{
    /**
     * @var \Tracking\Model\Notification Object describes the notification information.
     */
    public $notification;
}
