<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class DataTrackingResponseGetMultipleV1 extends Base
{
    /**
     * @var PaginationDataTrackingResponseGetMultipleV1 The Pagination holds the information for the pagination when the response contains multiple objects.
     */
    public $pagination;
    /**
     * @var \Tracking\Model\Tracking[] Array of 
     */
    public $trackings;
}
