<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class DataCourierConnectionResponseForGetCourierConnections extends Base
{
    /**
     * @var PaginationDataCourierConnectionResponseForGetCourierConnections
     */
    public $pagination;
    /**
     * @var \Tracking\Model\CourierConnection[]
     */
    public $courier_connections;
}
