<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class DestinationAddressEstimatedDeliveryDateRequest extends Base
{
    /**
     * @var string The country/region of the destination location where the package will be delivered. Use 3 letters of ISO 3166-1 country code.
     */
    public $country;
    /**
     * @var string|null State, province, or the equivalent location of the destination address where the package will be delivered.Either `destination_address.state` or `destination_address.postal_code` is required.
     */
    public $state;
    /**
     * @var string|null City of the destination address where the package will be delivered.
     */
    public $city;
    /**
     * @var string|null Postal code of the destination address.Either `destination_address.state` or `destination_address.postal_code` is required.
     */
    public $postal_code;
    /**
     * @var string|null Raw location of the destination address. A raw address will help AI to identify the accurate location of the destination address.
     */
    public $raw_location;
}
