<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class DetectCourierResponseData extends Base
{
    /**
     * @var int|null Total count of courier objects
     */
    public $total;

    /**
     * @var \Tracking\Model\Courier[]|null Array of  object.
     */
    public $couriers;
}
