<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

class DetectCourierResponse
{
    /**
     * @var array<string, string[]>
     */
    private readonly array $responseHeader;

    /**
     * @var DetectCourierResponseData
     */
    private readonly DetectCourierResponseData $data;

    /**
     * @param array<string, string[]> $responseHeader
     * @return DetectCourierResponse
     */
    public function setResponseHeader(array $responseHeader): DetectCourierResponse
    {
        $this->responseHeader = $responseHeader;
        return $this;
    }

    /**
     * @return array<string, string[]>
     */
    public function getResponseHeader(): array
    {
        return $this->responseHeader;
    }

    public function setData($data): DetectCourierResponse
    {
        $this->data = $data;
        return $this;
    }

    public function getData(): DetectCourierResponseData
    {
        return $this->data;
    }
}
