<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class EstimatedPickupEstimatedDeliveryDateRequest extends Base
{
    /**
     * @var string The local order time in the origin address time zone of the package.
     */
    public $order_time;
    /**
     * @var string|null Order cut off time in the origin address time zone. The default value set by AfterShip is 18:00:00.
     */
    public $order_cutoff_time;
    /**
     * @var array[] Operating days in a week. Number refers to the weekday.E.g., [1,2,3,4,5] means operating days are from Monday to Friday.AfterShip will set [1,2,3,4,5] as the default value.
     */
    public $business_days;
    /**
     * @var OrderProcessingTimeEstimatedPickupEstimatedDeliveryDateRequest 
     */
    public $order_processing_time;
}
