<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class EstimatedDeliveryDateRequestWeight extends Base
{
    /**
     * @var string|null The weight unit of the package.
     * @required
     */
    public $unit;

    /**
     * @var int|float|null The weight of the shipment.
     * @required
     */
    public $value;
}
