<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class EstimatedDeliveryDateResponse extends Base
{
    /**
     * @var string A string that acts as a unique identifier for the estimated delivery date value generated by AfterShip Predict API
     */
    public $id;
    /**
     * @var string AfterShip's unique code of courier. Please refer to https://track.aftership.com/couriers/download.
     */
    public $slug;
    /**
     * @var string|null AfterShip’s unique code represents carrier’s shipping and delivery options. Refer to .
     */
    public $service_type_name;
    /**
     * @var OriginAddressEstimatedDeliveryDateResponse The location from where the package is picked up by the carrier to be delivered to the final destination.
     */
    public $origin_address;
    /**
     * @var DestinationAddressEstimatedDeliveryDateResponse The final destination of the customer where the delivery will be made.
     */
    public $destination_address;
    /**
     * @var WeightEstimatedDeliveryDateResponse AfterShip uses this object to calculate the total weight of the order.
     */
    public $weight;
    /**
     * @var int|null The number of packages.
     */
    public $package_count;
    /**
     * @var string|null The local pickup time in the origin address time zone of the package.Either `pickup_time` or `estimated_pickup` is required.
     */
    public $pickup_time;
    /**
     * @var EstimatedPickupEstimatedDeliveryDateResponse The local pickup time of the package.Either `pickup_time` or `estimated_pickup` is required.
     */
    public $estimated_pickup;
    /**
     * @var string The estimated arrival date of the shipment, provided by AfterShip.
     */
    public $estimated_delivery_date;
    /**
     * @var int|float Indicates the confidence level and associated reason for an AI EDD prediction request. For a comprehensive list of confidence codes, refer to .
     */
    public $confidence_code;
    /**
     * @var string The earliest estimated delivery date of the shipment, provided by AfterShip.
     */
    public $estimated_delivery_date_min;
    /**
     * @var string The latest estimated delivery date of the shipment, provided by AfterShip.
     */
    public $estimated_delivery_date_max;
}
