<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class EventsCheckpoint extends Base
{
    /**
     * @var string Represents the event code.
     */
    public $code;
    /**
     * @var ReasonEventsCheckpoint Describes the specific reason that led to the event.
     */
    public $reason;
}
