<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class GetCourierConnectionsResponseData extends Base
{
    /**
     * @var \Tracking\Model\GetCourierConnectionsResponseDataPagination|null
     */
    public $pagination;

    /**
     * @var \Tracking\Model\CourierConnection[]|null
     */
    public $courier_connections;
}
