<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

class GetCourierConnectionsResponse
{
    /**
     * @var array<string, string[]>
     */
    private readonly array $responseHeader;

    /**
     * @var GetCourierConnectionsResponseData
     */
    private readonly GetCourierConnectionsResponseData $data;

    /**
     * @param array<string, string[]> $responseHeader
     * @return GetCourierConnectionsResponse
     */
    public function setResponseHeader(array $responseHeader): GetCourierConnectionsResponse
    {
        $this->responseHeader = $responseHeader;
        return $this;
    }

    /**
     * @return array<string, string[]>
     */
    public function getResponseHeader(): array
    {
        return $this->responseHeader;
    }

    public function setData($data): GetCourierConnectionsResponse
    {
        $this->data = $data;
        return $this;
    }

    public function getData(): GetCourierConnectionsResponseData
    {
        return $this->data;
    }
}
