<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

class GetCouriersResponse
{
    /**
     * @var array<string, string[]>
     */
    private readonly array $responseHeader;

    /**
     * @var GetCouriersResponseData
     */
    private readonly GetCouriersResponseData $data;

    /**
     * @param array<string, string[]> $responseHeader
     * @return GetCouriersResponse
     */
    public function setResponseHeader(array $responseHeader): GetCouriersResponse
    {
        $this->responseHeader = $responseHeader;
        return $this;
    }

    /**
     * @return array<string, string[]>
     */
    public function getResponseHeader(): array
    {
        return $this->responseHeader;
    }

    public function setData($data): GetCouriersResponse
    {
        $this->data = $data;
        return $this;
    }

    public function getData(): GetCouriersResponseData
    {
        return $this->data;
    }
}
