<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

class GetCouriersQuery extends \Tracking\Model\Base\QueryBase
{
    /**
     * @var bool|null get user activated couriers
     */
    public $active;
    /**
     * @var string|null Unique courier code Use comma for multiple values. (Example: dhl,ups,usps)
     */
    public $slug;

    public function setActive(string $active): GetCouriersQuery
    {
        $this->active = $active;
        return $this;
    }
    public function setSlug(string $slug): GetCouriersQuery
    {
        $this->slug = $slug;
        return $this;
    }
}
