<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

class GetTrackingByIdResponse
{
    /**
     * @var array<string, string[]>
     */
    private readonly array $responseHeader;

    /**
     * @var Tracking
     */
    private readonly Tracking $data;

    /**
     * @param array<string, string[]> $responseHeader
     * @return GetTrackingByIdResponse
     */
    public function setResponseHeader(array $responseHeader): GetTrackingByIdResponse
    {
        $this->responseHeader = $responseHeader;
        return $this;
    }

    /**
     * @return array<string, string[]>
     */
    public function getResponseHeader(): array
    {
        return $this->responseHeader;
    }

    public function setData($data): GetTrackingByIdResponse
    {
        $this->data = $data;
        return $this;
    }

    public function getData(): Tracking
    {
        return $this->data;
    }
}
