<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

class GetTrackingsResponse
{
    /**
     * @var array<string, string[]>
     */
    private readonly array $responseHeader;

    /**
     * @var GetTrackingsResponseData
     */
    private readonly GetTrackingsResponseData $data;

    /**
     * @param array<string, string[]> $responseHeader
     * @return GetTrackingsResponse
     */
    public function setResponseHeader(array $responseHeader): GetTrackingsResponse
    {
        $this->responseHeader = $responseHeader;
        return $this;
    }

    /**
     * @return array<string, string[]>
     */
    public function getResponseHeader(): array
    {
        return $this->responseHeader;
    }

    public function setData($data): GetTrackingsResponse
    {
        $this->data = $data;
        return $this;
    }

    public function getData(): GetTrackingsResponseData
    {
        return $this->data;
    }
}
