<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

enum MarkTrackingCompletedByIdRequestReason: string
{
    case DELIVERED = "DELIVERED";
    case LOST = "LOST";
    case RETURNED_TO_SENDER = "RETURNED_TO_SENDER";
}
