<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

enum MetaType: string
{
    case BAD_REQUEST = "BadRequest";
    case UNAUTHORIZED = "Unauthorized";
    case FORBIDDEN = "Forbidden";
    case NOT_FOUND = "NotFound";
    case TOO_MANY_REQUESTS = "TooManyRequests";
    case INTERNAL_ERROR = "InternalError";
}
