<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class Meta extends Base
{
    /**
     * @var int|null meta code
     * @required
     */
    public $code;

    /**
     * @var string|null error message, only exist if the response status is not 2xx
     */
    public $message;

    /**
     * @var \Tracking\Model\MetaType|null error type, only exist if the response status is not 2xx
     */
    public $type;
}
