<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class MetaV1 extends Base
{
    /**
     * @var int meta code
     */
    public $code;
    /**
     * @var string error message, only exist if the response status is not 2xx
     */
    public $message;
    /**
     * @var string|null|string error type, only exist if the response status is not 2xx
     */
    public $type;
}
