<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class NotificationRequestV1 extends Base
{
    /**
     * @var string[] Email address(es) to receive email notifications.Accept either array or comma separated as input.
     */
    public $emails;
    /**
     * @var string[] The phone number(s) to receive sms notifications.  Enter `+` and `area code` before phone number.Accept either array or comma separated as input.
     */
    public $smses;
}
