<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class Notification extends Base
{
    /**
     * @var array[] Email address(es) to receive email notifications.
     */
    public $emails;
    /**
     * @var array[] The phone number(s) to receive sms notifications.
     */
    public $smses;
}
