<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class NotificationResponseV1 extends Base
{
    /**
     * @var \Tracking\Model\MetaV1 Meta data
     */
    public $meta;
    /**
     * @var DataNotificationResponseV1
     */
    public $data;
}
