<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class OriginAddressEstimatedDeliveryDateResponse extends Base
{
    /**
     * @var string The country/region of the origin location from where the package is picked up by the carrier to be delivered to the final destination. Use 3 letters of ISO 3166-1 country/region code.
     */
    public $country;
    /**
     * @var string|null State, province, or the equivalent location of the origin address. Use 3 letters of ISO 3166-1 country/region code for countries/regions without state. Either `origin_address.state` or `origin_address.postal_code` is required.
     */
    public $state;
    /**
     * @var string|null City of the origin address. Use 3 letters of ISO 3166-1 country/region code for countries/regions without City.
     */
    public $city;
    /**
     * @var string|null Postal code of the origin address. Use 3 letters of ISO 3166-1 country/region code for countries/regions without postal code. Either `origin_address.state` or `origin_address.postal_code` is required.
     */
    public $postal_code;
    /**
     * @var string|null Raw location of the origin address. A raw address will help AI to identify the accurate location of the origin address.
     */
    public $raw_location;
}
