<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

class PaginationCursor
{
    public $total;
    public $next_cursor;
    public $previous_cursor;

    public static function fromArray(array $data)
    {
        if (empty($data)) {
            return null;
        }
        $pagination = new PaginationCursor();
        $pagination->total = $data['total'] ?? null;
        $pagination->next_cursor = $data['next_cursor'];
        $pagination->previous_cursor = $data['previous_cursor'];
        return $pagination;
    }
}
