<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

class PaginationPage
{
    public $total;
    public $page;
    public $limit;
    public $has_next_page;

    public static function fromArray(array $data)
    {
        if (empty($data)) {
            return null;
        }
        $paginationPage = new PaginationPage();
        $paginationPage->total = $data['count'] ?? $data['total'] ?? null;
        $paginationPage->page = $data['page'] ?? null;
        $paginationPage->limit = $data['limit'] ?? null;
        $paginationPage->has_next_page = $data['has_next_page'] ?? null;
        return $paginationPage;
    }
}
