<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class PaginationDataTrackingResponseGetMultipleV1 extends Base
{
    /**
     * @var int The total number of trackings.
     */
    public $total;
    /**
     * @var string A string representing the cursor value for the next page of results.
     */
    public $next_cursor;
    /**
     * @var bool To indicate if next page is available.
     */
    public $has_next_page;
}
