<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

class PostCourierConnectionsResponse
{
    /**
     * @var array<string, string[]>
     */
    private readonly array $responseHeader;

    /**
     * @var CourierConnection
     */
    private readonly CourierConnection $data;

    /**
     * @param array<string, string[]> $responseHeader
     * @return PostCourierConnectionsResponse
     */
    public function setResponseHeader(array $responseHeader): PostCourierConnectionsResponse
    {
        $this->responseHeader = $responseHeader;
        return $this;
    }

    /**
     * @return array<string, string[]>
     */
    public function getResponseHeader(): array
    {
        return $this->responseHeader;
    }

    public function setData($data): PostCourierConnectionsResponse
    {
        $this->data = $data;
        return $this;
    }

    public function getData(): CourierConnection
    {
        return $this->data;
    }
}
