<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class PredictBatchResponseData extends Base
{
    /**
     * @var \Tracking\Model\EstimatedDeliveryDateResponse[]|null
     * @required
     */
    public $estimated_delivery_dates;
}
