<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

class PredictBatchResponse
{
    /**
     * @var array<string, string[]>
     */
    private readonly array $responseHeader;

    /**
     * @var PredictBatchResponseData
     */
    private readonly PredictBatchResponseData $data;

    /**
     * @param array<string, string[]> $responseHeader
     * @return PredictBatchResponse
     */
    public function setResponseHeader(array $responseHeader): PredictBatchResponse
    {
        $this->responseHeader = $responseHeader;
        return $this;
    }

    /**
     * @return array<string, string[]>
     */
    public function getResponseHeader(): array
    {
        return $this->responseHeader;
    }

    public function setData($data): PredictBatchResponse
    {
        $this->data = $data;
        return $this;
    }

    public function getData(): PredictBatchResponseData
    {
        return $this->data;
    }
}
