<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

class PredictResponse
{
    /**
     * @var array<string, string[]>
     */
    private readonly array $responseHeader;

    /**
     * @var EstimatedDeliveryDateResponse
     */
    private readonly EstimatedDeliveryDateResponse $data;

    /**
     * @param array<string, string[]> $responseHeader
     * @return PredictResponse
     */
    public function setResponseHeader(array $responseHeader): PredictResponse
    {
        $this->responseHeader = $responseHeader;
        return $this;
    }

    /**
     * @return array<string, string[]>
     */
    public function getResponseHeader(): array
    {
        return $this->responseHeader;
    }

    public function setData($data): PredictResponse
    {
        $this->data = $data;
        return $this;
    }

    public function getData(): EstimatedDeliveryDateResponse
    {
        return $this->data;
    }
}
