<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class ReasonEventsCheckpoint extends Base
{
    /**
     * @var string The code of the reason. 
     */
    public $code;
}
