<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class ShipmentWeightTracking extends Base
{
    /**
     * @var string The unit in which the value field is expressed.
     */
    public $unit;
    /**
     * @var int|float The total amount of shipment weight.
     */
    public $value;
}
