<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class SlugGroupV1
{
    const AMAZON_GROUP = "amazon-group";
    const FEDEX_GROUP = "fedex-group";
    const TOLL_GROUP = "toll-group";
    const TAQBIN_GROUP = "taqbin-group";
    const TNT_GROUP = "tnt-group";
    const CJ_GROUP = "cj-group";
    const HERMES_GROUP = "hermes-group";
    const DPD_GROUP = "dpd-group";
    const GLS_GROUP = "gls-group";
    const DHL_GROUP = "dhl-group";
    const FASTWAY_GROUP = "fastway-group";
    const ASENDIA_GROUP = "asendia-group";
}
