<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

enum SlugGroup: string
{
    case AMAZON_GROUP = "amazon-group";
    case FEDEX_GROUP = "fedex-group";
    case TOLL_GROUP = "toll-group";
    case TAQBIN_GROUP = "taqbin-group";
    case TNT_GROUP = "tnt-group";
    case CJ_GROUP = "cj-group";
    case HERMES_GROUP = "hermes-group";
    case DPD_GROUP = "dpd-group";
    case GLS_GROUP = "gls-group";
    case DHL_GROUP = "dhl-group";
    case FASTWAY_GROUP = "fastway-group";
    case ASENDIA_GROUP = "asendia-group";
}
