<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

enum Tag: string
{
    case PENDING = "Pending";
    case INFO_RECEIVED = "InfoReceived";
    case IN_TRANSIT = "InTransit";
    case OUT_FOR_DELIVERY = "OutForDelivery";
    case ATTEMPT_FAIL = "AttemptFail";
    case DELIVERED = "Delivered";
    case AVAILABLE_FOR_PICKUP = "AvailableForPickup";
    case EXCEPTION = "Exception";
    case EXPIRED = "Expired";
}
