<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class TagV1
{
    const PENDING = "Pending";
    const INFO_RECEIVED = "InfoReceived";
    const IN_TRANSIT = "InTransit";
    const OUT_FOR_DELIVERY = "OutForDelivery";
    const ATTEMPT_FAIL = "AttemptFail";
    const DELIVERED = "Delivered";
    const AVAILABLE_FOR_PICKUP = "AvailableForPickup";
    const EXCEPTION = "Exception";
    const EXPIRED = "Expired";
}
