<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class TrackingShipmentDimensions extends Base
{
    /**
     * @var string|null The unit in which the dimension values are expressed. Allowed values: cm, in
     */
    public $unit;

    /**
     * @var int|float|null The length of the shipment package.
     */
    public $length;

    /**
     * @var int|float|null The width of the shipment package.
     */
    public $width;

    /**
     * @var int|float|null The height of the shipment package.
     */
    public $height;
}
