<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class TrackingResponseForGetTrackings extends Base
{
    /**
     * @var \Tracking\Model\Meta|null Meta data
     * @required
     */
    public $meta;

    /**
     * @var \Tracking\Model\TrackingResponseForGetTrackingsData|null
     */
    public $data;
}
