<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class TrackingAftershipEstimatedDeliveryDate extends Base
{
    /**
     * @var string|null The estimated arrival date of the shipment.
     */
    public $estimated_delivery_date;

    /**
     * @var int|float|null Indicates the confidence level and associated reason for an AI EDD prediction request. For a comprehensive list of confidence codes, refer to .
     */
    public $confidence_code;

    /**
     * @var string|null Earliest estimated delivery date of the shipment.
     */
    public $estimated_delivery_date_min;

    /**
     * @var string|null Latest estimated delivery date of the shipment.
     */
    public $estimated_delivery_date_max;
}
