<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

enum TrackingCustomEstimatedDeliveryDateType: string
{
    case RANGE = "range";
    case SPECIFIC = "specific";
}
