<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class TrackingForwardShipment extends Base
{
    /**
     * @var string|null AfterShip system-assigned unique identifier of the linked outbound shipment.
     */
    public $id;
}
