<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class TrackingProofOfDelivery extends Base
{
    /**
     * @var string|null The file type of the proof of delivery record. Currently, only images are supported.
     */
    public $type;

    /**
     * @var string|null The URL of the proof of delivery record.
     */
    public $url;
}
