<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class TrackingCarbonEmissions extends Base
{
    /**
     * @var string|null The unit in which the value field is expressed. Allowed values: kg
     */
    public $unit;

    /**
     * @var int|float|null The total amount of carbon emissions
     */
    public $value;
}
