<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class TrackingResponse extends Base
{
    /**
     * @var \Tracking\Model\Meta|null Meta data
     * @required
     */
    public $meta;

    /**
     * @var \Tracking\Model\Tracking|null Object describes the tracking information.<div style="display:none; height: 0"></div>
     * @required
     */
    public $data;
}
