<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class TrackingReturnShipment extends Base
{
    /**
     * @var string|null AfterShip system-assigned unique identifier of the linked return shipment.This field is only returned when both of the following conditions are met:1. AfterShip has detected a linked return shipment.2. The Auto-import for return shipments feature is enabled in your AfterShip account.When auto-import is disabled, `id` will not be returned, but `tracking_number` and `slug` may still be present.To enable this feature, go to .
     */
    public $id;

    /**
     * @var string|null Carrier-assigned tracking number of the linked return shipment. Can be used together with `return_shipment.slug` to create a new tracking subscription and retrieve the return shipment's checkpoints.
     */
    public $tracking_number;

    /**
     * @var string|null Carrier slug (identifier) of the linked return shipment. Can be used together with `return_shipment.tracking_number` to subscribe to tracking updates for the return shipment.
     */
    public $slug;
}
