<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class TrackingMultiPieceInfoPieces extends Base
{
    /**
     * @var string|null AfterShip system-assigned unique identifier for the piece.
     */
    public $tracking_id;

    /**
     * @var string|null Carrier-assigned tracking number for the piece.
     */
    public $tracking_number;

    /**
     * @var \Tracking\Model\TrackingMultiPieceInfoPiecesType|null Type of the piece within the MPS: `master` or `child`.
     */
    public $type;

    /**
     * @var bool|null Indicates whether the tracking number can be used to retrieve tracking updates on the carrier's side. If not, it means the carrier can only return a child tracking number, but cannot independently provide tracking updates for the sub-shipment. In this case, it is not recommended for you to import this tracking number into AfterShip for tracking.
     */
    public $trackable;
}
