<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

enum TrackingLatestEstimatedDeliverySource: string
{
    case CARRIER_EDD = "Carrier EDD";
    case AFTER_SHIP_EDD = "AfterShip EDD";
    case CUSTOM_EDD = "Custom EDD";
    case ORDER_EDD = "Order EDD";
}
