<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

enum TrackingSignatureRequirement: string
{
    case SIGNATURE_REQUIRED = "signature_required";
    case ADULT_SIGNATURE_REQUIRED = "adult_signature_required";
    case INDIRECT_SIGNATURE_REQUIRED = "indirect_signature_required";
    case NO_SIGNATURE_REQUIRED = "no_signature_required";
    case NULL = "null";
}
