<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class TrackingResponse extends Base
{
    /**
     * @var \Tracking\Model\Meta Meta data
     */
    public $meta;
    /**
     * @var \Tracking\Model\Tracking Object describes the tracking information.<div style="display:none; height: 0"></div>
     */
    public $data;
}
