<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class TrackingMultiPieceInfo extends Base
{
    /**
     * @var \Tracking\Model\TrackingMultiPieceInfoType|null Indicates the role of the current tracking object within the multi-piece shipment.Possible values:- `master`: The main tracking number representing the entire shipment. It may not always exist.- `child`: A sub-tracking number belonging to one of the pieces in the shipment.
     */
    public $type;

    /**
     * @var \Tracking\Model\TrackingMultiPieceInfoPieces[]|null List of all pieces in the MPS, including the master and all child pieces.
     */
    public $pieces;
}
