<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class TrackingResponseForGetTrackingsData extends Base
{
    /**
     * @var \Tracking\Model\TrackingResponseForGetTrackingsDataPagination|null The Pagination holds the information for the pagination when the response contains multiple objects.
     */
    public $pagination;

    /**
     * @var \Tracking\Model\Tracking[]|null Array of
     */
    public $trackings;
}
