<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

class UpdateTrackingByIdRequest extends Base
{
    /**
     * @var string|null By default this field shows the `tracking_number`, but you can customize it as you wish with any info (e.g. the order number).
     */
    public $title;

    /**
     * @var string|null A globally-unique identifier for the order.
     */
    public $order_id;

    /**
     * @var string|null The URL for the order in your system or store.
     */
    public $order_id_path;

    /**
     * @var array|null Custom fields that accept an object with string field. In order to protect the privacy of your customers, do not include any
     */
    public $custom_fields;

    /**
     * @var string|null Text field for the note.Input `""` to clear the value of this field.
     */
    public $note;

    /**
     * @var string|null The recipient’s language. If you set up AfterShip notifications in different languages, we use this to send the recipient tracking updates in their preferred language. Use an  to specify the language.
     */
    public $language;

    /**
     * @var string|null The promised delivery date of the order. It uses the formats:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ
     */
    public $order_promised_delivery_date;

    /**
     * @var \Tracking\Model\UpdateTrackingByIdRequestDeliveryType|null Shipment delivery type- `pickup_at_store`- `pickup_at_courier`- `door_to_door`
     */
    public $delivery_type;

    /**
     * @var string|null Shipment pickup location for receiver
     */
    public $pickup_location;

    /**
     * @var string|null Shipment pickup note for receiver
     */
    public $pickup_note;

    /**
     * @var string|null Unique code of each courier. Provide a single courier.(https://admin.aftership.com/settings/couriers). Get a list of courier slug using
     */
    public $slug;

    /**
     * @var string|null Additional field required by some carriers to retrieve the tracking info. The shipper’s carrier account number. Refer to our article on  for more details.
     */
    public $tracking_account_number;

    /**
     * @var string|null Additional field required by some carriers to retrieve the tracking info. A type of tracking credential required by some carriers. Refer to our article on  for more details.
     */
    public $tracking_key;

    /**
     * @var string|null The date and time when the shipment is shipped by the merchant and ready for pickup by the carrier. The field supports the following formats:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZThe field serves two key purposes:- Calculate processing time metrics in the Order-to-delivery Analytics dashboard. To ensure accurate analytics, it's recommended to include timezone information when configuring this value- Required by certain carriers to retrieve tracking information as an additional tracking field.
     */
    public $tracking_ship_date;

    /**
     * @var string|null A unique, human-readable identifier for the order.
     */
    public $order_number;

    /**
     * @var string|null Order date in YYYY-MM-DDTHH:mm:ssZ format. e.g. 2021-07-26T11:23:51-05:00
     */
    public $order_date;

    /**
     * @var string|null The carrier service type for the shipment. If you provide info for this field, AfterShip will not update it with info from the carrier.
     */
    public $shipment_type;

    /**
     * @var string|null The  for more details.
     */
    public $origin_country_region;

    /**
     * @var string|null The state of the sender’s address. This can help AfterShip with various functions like tracking, carrier auto-detection and auto-correction, calculating an EDD, etc.
     */
    public $origin_state;

    /**
     * @var string|null The city of the sender’s address. This can help AfterShip with various functions like tracking, carrier auto-detection and auto-correction, calculating an EDD, etc.
     */
    public $origin_city;

    /**
     * @var string|null The postal of the sender’s address. This can help AfterShip with various functions like tracking, carrier auto-detection and auto-correction, calculating an EDD, etc.
     */
    public $origin_postal_code;

    /**
     * @var string|null The sender address that the shipment is shipping from. This can help AfterShip with various functions like tracking, carrier auto-detection and auto-correction, calculating an EDD, etc.
     */
    public $origin_raw_location;

    /**
     * @var string|null The  for more details.
     */
    public $destination_country_region;

    /**
     * @var string|null The state of the recipient’s address. This can help AfterShip with various functions like tracking, carrier auto-detection and auto-correction, calculating an EDD, etc. Also the additional field required by some carriers to retrieve the tracking info. The state/province of the recipient’s address. Refer to our article on  for more details.
     */
    public $destination_state;

    /**
     * @var string|null The city of the recipient’s address. This can help AfterShip with various functions like tracking, carrier auto-detection and auto-correction, calculating an EDD, etc.
     */
    public $destination_city;

    /**
     * @var string|null The postal of the recipient’s address. This can help AfterShip with various functions like tracking, carrier auto-detection and auto-correction, calculating an EDD, etc. Also the additional field required by some carriers to retrieve the tracking info. The postal code of the recipient’s address. Refer to our article on  for more details.
     */
    public $destination_postal_code;

    /**
     * @var string|null The shipping address that the shipment is shipping to. This can help AfterShip with various functions like tracking, carrier auto-detection and auto-correction, calculating an EDD, etc.
     */
    public $destination_raw_location;

    /**
     * @var string|null The location_id refers to the place where you fulfilled the items.  - If you provide a location_id, the system will automatically use it as the tracking's origin address. However, passing both location_id and any origin address information simultaneously is not allowed.- Please make sure you add your locations .
     */
    public $location_id;

    /**
     * @var string|null The shipping_method string refers to the chosen method for delivering the package. Merchants typically offer various shipping methods to consumers during the checkout process, such as, Local Delivery, Free Express Worldwide Shipping, etc.
     */
    public $shipping_method;

    /**
     * @var \Tracking\Model\UpdateTrackingByIdRequestCustomers[]|null The field contains the customer information associated with the tracking. A maximum of three customer objects are allowed.
     */
    public $customers;
}
