<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model;

use Tracking\Model\Base\Base;

enum UpdateTrackingByIdRequestShipmentDirection: string
{
    case FORWARD = "forward";
    case RETURN = "return";
}
