<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\API\Tracking;

use Tracking\Model\Base\Base;

class AftershipEstimatedDeliveryDateDeleteTrackingBySlugTrackingNumberResponse extends Base
{
    /**
     * @var string The estimated arrival date of the shipment.
     */
    public $estimated_delivery_date;
    /**
     * @var int|float Indicates the confidence level and associated reason for an AI EDD prediction request. For a comprehensive list of confidence codes, refer to .
     */
    public $confidence_code;
    /**
     * @var string Earliest estimated delivery date of the shipment.
     */
    public $estimated_delivery_date_min;
    /**
     * @var string Latest estimated delivery date of the shipment.
     */
    public $estimated_delivery_date_max;
}
