<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\API\Tracking;

use Tracking\Model\Base\Base;

class CarbonEmissionsMarkTrackingCompletedBySlugTrackingNumberResponse extends Base
{
    /**
     * @var string The unit in which the value field is expressed. Allowed values: kg
     */
    public $unit;
    /**
     * @var int|float The total amount of carbon emissions
     */
    public $value;
}
