<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\API\Tracking;

use Tracking\Model\Base\Base;

class CreateTrackingRequest extends Base
{
    /**
     * @var string Tracking number of a shipment.Duplicated tracking numbers, tracking numbers with invalid tracking number format will not be accepted.We only accept tracking numbers with length from 4 to 100We currently support the following characters in a tracking number:- A - Z- 0 - 9- `-` (Hyphen)- . (Period)- _ (Underscore)- / (Slash)
     */
    public $tracking_number;
    /**
     * @var string Unique courier code. Get courier codes .
     */
    public $slug;
    /**
     * @var string By default this field shows the `tracking_number`, but you can customize it as you wish with any info (e.g. the order number).
     */
    public $title;
    /**
     * @var string A globally-unique identifier for the order.
     */
    public $order_id;
    /**
     * @var string The URL for the order in your system or store.
     */
    public $order_id_path;
    /**
     * @var array|null Custom fields that accept an object with string field. In order to protect the privacy of your customers, do not include any 
     */
    public $custom_fields;
    /**
     * @var string The recipient’s language. If you set up AfterShip notifications in different languages, we use this to send the recipient tracking updates in their preferred language. Use an  to specify the language.
     */
    public $language;
    /**
     * @var string The promised delivery date of the order. It uses the formats:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ
     */
    public $order_promised_delivery_date;
    /**
     * @var string|null|string Shipment delivery type- pickup_at_store- pickup_at_courier- door_to_door
     */
    public $delivery_type;
    /**
     * @var string Shipment pickup location for receiver
     */
    public $pickup_location;
    /**
     * @var string Shipment pickup note for receiver
     */
    public $pickup_note;
    /**
     * @var string Additional field required by some carriers to retrieve the tracking info. The shipper’s carrier account number. Refer to our article on  for more details.
     */
    public $tracking_account_number;
    /**
     * @var string Additional field required by some carriers to retrieve the tracking info. A type of tracking credential required by some carriers. Refer to our article on  for more details.
     */
    public $tracking_key;
    /**
     * @var string Additional field required by some carriers to retrieve the tracking info. The date the shipment was sent, using the format YYYYMMDD. Refer to our article on  for more details.
     */
    public $tracking_ship_date;
    /**
     * @var array[] Email address(es) to receive email notifications. Accept either array. Supports up to 3 email addresses.
     */
    public $emails;
    /**
     * @var array[] The phone number(s) to receive sms notifications.  Enter `+` andarea `code before` phone number. Accept either array. Supports up to 3 phone numbers.
     */
    public $smses;
    /**
     * @var string Customer name of the tracking.
     */
    public $customer_name;
    /**
     * @var string The  for more details.
     */
    public $origin_country_iso3;
    /**
     * @var string The state of the sender’s address. This can help AfterShip with various functions like tracking, carrier auto-detection and auto-correction, calculating an EDD, etc.
     */
    public $origin_state;
    /**
     * @var string The city of the sender’s address. This can help AfterShip with various functions like tracking, carrier auto-detection and auto-correction, calculating an EDD, etc.
     */
    public $origin_city;
    /**
     * @var string The postal of the sender’s address. This can help AfterShip with various functions like tracking, carrier auto-detection and auto-correction, calculating an EDD, etc.
     */
    public $origin_postal_code;
    /**
     * @var string The sender address that the shipment is shipping from. This can help AfterShip with various functions like tracking, carrier auto-detection and auto-correction, calculating an EDD, etc.
     */
    public $origin_raw_location;
    /**
     * @var string The  for more details.
     */
    public $destination_country_iso3;
    /**
     * @var string The state of the recipient’s address. This can help AfterShip with various functions like tracking, carrier auto-detection and auto-correction, calculating an EDD, etc. Also the additional field required by some carriers to retrieve the tracking info. The state/province of the recipient’s address. Refer to our article on  for more details.
     */
    public $destination_state;
    /**
     * @var string The city of the recipient’s address. This can help AfterShip with various functions like tracking, carrier auto-detection and auto-correction, calculating an EDD, etc.
     */
    public $destination_city;
    /**
     * @var string The postal of the recipient’s address. This can help AfterShip with various functions like tracking, carrier auto-detection and auto-correction, calculating an EDD, etc. Also the additional field required by some carriers to retrieve the tracking info. The postal code of the recipient’s address. Refer to our article on  for more details.
     */
    public $destination_postal_code;
    /**
     * @var string The shipping address that the shipment is shipping to. This can help AfterShip with various functions like tracking, carrier auto-detection and auto-correction, calculating an EDD, etc.
     */
    public $destination_raw_location;
    /**
     * @var string Text field for the note
     */
    public $note;
    /**
     * @var string|null|\Tracking\Model\SlugGroupV1 Slug group is a group of slugs which belong to same courier. For example, when you inpit "fedex-group" as slug_group, AfterShip will detect the tracking with "fedex-uk", "fedex-fims", and other slugs which belong to "fedex". It cannot be used with slug at the same time. (
     */
    public $slug_group;
    /**
     * @var string Order date in YYYY-MM-DDTHH:mm:ssZ format. e.g. 2021-07-26T11:23:51-05:00
     */
    public $order_date;
    /**
     * @var string A unique, human-readable identifier for the order.
     */
    public $order_number;
    /**
     * @var string The carrier service type for the shipment. If you provide info for this field, AfterShip will not update it with info from the carrier.
     */
    public $shipment_type;
    /**
     * @var array[] Used to add tags to your shipments to help categorize and filter them easily.
     */
    public $shipment_tags;
    /**
     * @var string If you’ve connected multiple accounts for a single carrier on AfterShip, you can now use the courier_connection_id field to tell AfterShip which carrier account you’ve used to handle a shipment so we can track it. (
     */
    public $courier_connection_id;
    /**
     * @var NextCouriersCreateTrackingRequest[] If a shipment has multiple carriers, you can use the next_couriers field to tell AfterShip who the second carrier is. This is useful if the first carrier does not send us this information. 
     */
    public $next_couriers;
    /**
     * @var string (Legacy) Replaced by `origin_country_iso3`. Additional field required by some carriers to retrieve the tracking info. The origin country/region of the shipment. Refer to our article on  for more details.
     */
    public $tracking_origin_country;
    /**
     * @var string (Legacy) Replaced by `destination_country_iso3`. Additional field required by some carriers to retrieve the tracking info. The destination country/region of the shipment. Refer to our article on  for more details.
     */
    public $tracking_destination_country;
    /**
     * @var string (Legacy) Replaced by `destination_postal_code`. Additional field required by some carriers to retrieve the tracking info. The postal code of the recipient’s address. Refer to our article on  for more details.
     */
    public $tracking_postal_code;
    /**
     * @var string (Legacy) Replaced by `destination_state`. Additional field required by some carriers to retrieve the tracking info. The state/province of the recipient’s address. Refer to our article on  for more details.
     */
    public $tracking_state;
    /**
     * @var string The location_id refers to the place where you fulfilled the items.  - If you provide a location_id, the system will automatically use it as the tracking's origin address. However, passing both location_id and any origin address information simultaneously is not allowed.- Please make sure you add your locations .
     */
    public $location_id;
    /**
     * @var string The shipping_method string refers to the chosen method for delivering the package. Merchants typically offer various shipping methods to consumers during the checkout process, such as, Local Delivery, Free Express Worldwide Shipping, etc
     */
    public $shipping_method;
}
