<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\API\Tracking;

use Tracking\Model\Base\Base;

class CustomFieldsUpdateTrackingBySlugTrackingNumberRequest extends Base
{
}
