<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\API\Tracking;

use Tracking\Model\Base\Base;

class CustomersUpdateTrackingByIdRequest extends Base
{
    /**
     * @var string The  role of the customer, indicating whether the customer is  an individual or a company.
     */
    public $role;
    /**
     * @var string Customer name associated with the tracking.
     */
    public $name;
    /**
     * @var string The phone number(s) to receive SMS notifications. Phone numbers should begin with a `+` sign and include the area code.
     */
    public $phone_number;
    /**
     * @var string Email address(es) to receive email notifications.
     */
    public $email;
    /**
     * @var string The preferred language of the customer. If you have set up AfterShip notifications in different languages, we use this to send the tracking updates to the customer in their preferred language.
     */
    public $language;
}
