<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\API\Tracking;

use Tracking\Model\Base\Base;

class DeleteTrackingByIdResponse extends Base
{
    /**
     * @var \Tracking\Model\PartialDeleteTracking Partial tracking model
     */
    public $tracking;
}
