<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\API\Tracking;

use Tracking\Model\Base\Base;

class GetTrackingBySlugTrackingNumberResponse extends Base
{
    /**
     * @var \Tracking\Model\Tracking Object describes the tracking information.<div style="display:none; height: 0"></div>
     */
    public $tracking;
}
