<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\API\Tracking;

class GetTrackingsResponse extends \Tracking\Model\Base\Base
{
    /**
     * @var \Tracking\Model\Tracking[]
     */
    public $trackings;

    /**
     * @var \Tracking\Model\PaginationPage
     */
    public $pagination;

    public function __construct(array $trackings, \Tracking\Model\PaginationPage $pagination)
    {
        $this->trackings = $trackings;
        $this->pagination = $pagination;
    }
}
