<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\API\Tracking;

use Tracking\Model\Base\Base;

class GetTrackingsResponse extends Base
{
    /**
     * @var PaginationGetTrackingsResponse The Pagination holds the information for the pagination when the response contains multiple objects.
     */
    public $pagination;
    /**
     * @var \Tracking\Model\Tracking[] Array of 
     */
    public $trackings;
}
