<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\API\Tracking;

class GetTrackingsQuery extends \Tracking\API\Base\QueryBase
{

    /**
     * @var string|null A string representing the cursor value for the current page of results.
     */
    public $cursor;
    /**
     * @var int|null Number of trackings each page contain. (Default: 100, Max: 200)
     */
    public $limit;
    /**
     * @var string|null Search the content of the tracking record fields: `tracking_number`, `title`, `order_id`, `customer_name`, `custom_fields`, `emails`, `smses`
     */
    public $keyword;
    /**
     * @var string|null Tracking number of shipments. Use comma to separate multiple values (Example: RA123456789US,LE123456789US). Supports up to 50 tracking numbers.
     */
    public $tracking_numbers;
    /**
     * @var string|null Unique courier code Use comma for multiple values. (Example: dhl,ups,usps)
     */
    public $slug;
    /**
     * @var int|null Total delivery time in days.- When the shipment is delivered: Transit time = Delivered date - Picked up date- When the shipment is not delivered: Transit time = Current date - Picked up dateValue as `null` for the shipment without pickup date.
     */
    public $transit_time;
    /**
     * @var string|null Origin country/region of trackings. Use ISO Alpha-3 (three letters). Use comma for multiple values. (Example: USA,HKG)
     */
    public $origin;
    /**
     * @var string|null Destination country/region of trackings. Use ISO Alpha-3 (three letters). Use comma for multiple values. (Example: USA,HKG)
     */
    public $destination;
    /**
     * @var string|null Current status of tracking. Values include `Pending`, `InfoReceived`, `InTransit`, `OutForDelivery`, `AttemptFail`, `Delivered`, `AvailableForPickup`, `Exception`, `Expired` (See tag definition)
     */
    public $tag;
    /**
     * @var string|null Start date and time of trackings created. AfterShip only stores data of 120 days.(Defaults: 30 days ago, Example: 2013-03-15T16:41:56+08:00)
     */
    public $created_at_min;
    /**
     * @var string|null End date and time of trackings created.(Defaults: now, Example: 2013-04-15T16:41:56+08:00)
     */
    public $created_at_max;
    /**
     * @var string|null Start date and time of trackings updated. (Example: 2013-04-15T16:41:56+08:00)
     */
    public $updated_at_min;
    /**
     * @var string|null End date and time of trackings updated. (Example: 2013-04-15T16:41:56+08:00)
     */
    public $updated_at_max;
    /**
     * @var string|null List of fields to include in the response. Use comma for multiple values. Available options: `title`, `order_id`, `tag`, `checkpoints`. Example: `title,order_id`
     */
    public $fields;
    /**
     * @var string|null Select return to sender, the value should be `true` or `false`, with optional comma separated.
     */
    public $return_to_sender;
    /**
     * @var string|null Destination country/region of trackings returned by courier. Use ISO Alpha-3 (three letters). Use comma for multiple values. (Example: USA,HKG)
     */
    public $courier_destination_country_iso3;
    /**
     * @var string|null Tags you added to your shipments to help categorize and filter them easily. Use a comma to separate multiple values (Example: a,b)
     */
    public $shipment_tags;
    /**
     * @var string|null A globally-unique identifier for the order. Use comma for multiple values.(Example: 6845a095a27a4caeb27487806f058add,4845a095a27a4caeb27487806f058abc)
     */
    public $order_id;

    public function setCursor(string $cursor): GetTrackingsQuery
    {
        $this->cursor = $cursor;
        return $this;
    }
    public function setLimit(string $limit): GetTrackingsQuery
    {
        $this->limit = $limit;
        return $this;
    }
    public function setKeyword(string $keyword): GetTrackingsQuery
    {
        $this->keyword = $keyword;
        return $this;
    }
    public function setTrackingNumbers(string $tracking_numbers): GetTrackingsQuery
    {
        $this->tracking_numbers = $tracking_numbers;
        return $this;
    }
    public function setSlug(string $slug): GetTrackingsQuery
    {
        $this->slug = $slug;
        return $this;
    }
    public function setTransitTime(string $transit_time): GetTrackingsQuery
    {
        $this->transit_time = $transit_time;
        return $this;
    }
    public function setOrigin(string $origin): GetTrackingsQuery
    {
        $this->origin = $origin;
        return $this;
    }
    public function setDestination(string $destination): GetTrackingsQuery
    {
        $this->destination = $destination;
        return $this;
    }
    public function setTag(string $tag): GetTrackingsQuery
    {
        $this->tag = $tag;
        return $this;
    }
    public function setCreatedAtMin(string $created_at_min): GetTrackingsQuery
    {
        $this->created_at_min = $created_at_min;
        return $this;
    }
    public function setCreatedAtMax(string $created_at_max): GetTrackingsQuery
    {
        $this->created_at_max = $created_at_max;
        return $this;
    }
    public function setUpdatedAtMin(string $updated_at_min): GetTrackingsQuery
    {
        $this->updated_at_min = $updated_at_min;
        return $this;
    }
    public function setUpdatedAtMax(string $updated_at_max): GetTrackingsQuery
    {
        $this->updated_at_max = $updated_at_max;
        return $this;
    }
    public function setFields(string $fields): GetTrackingsQuery
    {
        $this->fields = $fields;
        return $this;
    }
    public function setReturnToSender(string $return_to_sender): GetTrackingsQuery
    {
        $this->return_to_sender = $return_to_sender;
        return $this;
    }
    public function setCourierDestinationCountryIso3(string $courier_destination_country_iso3): GetTrackingsQuery
    {
        $this->courier_destination_country_iso3 = $courier_destination_country_iso3;
        return $this;
    }
    public function setShipmentTags(string $shipment_tags): GetTrackingsQuery
    {
        $this->shipment_tags = $shipment_tags;
        return $this;
    }
    public function setOrderId(string $order_id): GetTrackingsQuery
    {
        $this->order_id = $order_id;
        return $this;
    }
}
