<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\API\Tracking;

use Tracking\Model\Base\Base;

class LastMileUpdateTrackingByIdResponse extends Base
{
    /**
     * @var string The tracking number of the last-mile carrier.
     */
    public $tracking_number;
    /**
     * @var string The unique code of the carrier responsible for the last-mile of the shipment.  Find all the courier slugs .
     */
    public $slug;
    /**
     * @var string|null The transit time for the last-mile of a shipment in days. This field is calculated based on whether the handed_over_to_last_mile_carrier or the received_by_last_mile_carrier event is detected by AfterShip. The handover event date is used to calculate the last-mile transit time.- Last mile transit time (in days)= Delivered date - Handover date
     */
    public $transit_time;
    /**
     * @var string The field contains the official tracking URL of the last-mile carrier, if available. The language parameter of this link is determined by the destination country/region and the language associated with the shipment. If the destination country/region and language data is unavailable, AfterShip will default the language parameter to "US".
     */
    public $courier_tracking_link;
    /**
     * @var string The field provides the link for modifying delivery instructions (such as delivery date and shipping address), if supported by the last-mile carrier. The language parameter of this link is determined by the destination country/region and the language associated with the shipment. If the destination country/region and language data is unavailable, AfterShip will default the language parameter to "US".
     */
    public $courier_redirect_link;
    /**
     * @var string|null|string The field indicates the source of last-mile carrier.
     */
    public $source;
}
