<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\API\Tracking;

use Tracking\Model\Base\Base;

class LastMileCreateTrackingRequest extends Base
{
    /**
     * @var string The tracking number of the last-mile carrier.
     */
    public $tracking_number;
    /**
     * @var string The unique code of the carrier responsible for the last-mile of the shipment.  Find all the courier slugs .
     */
    public $slug;
}
