<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\API\Tracking;

use Tracking\Model\Base\Base;

class UpdateTrackingByIdRequest extends Base
{
    /**
     * @var array[] The phone number(s) to receive sms notifications.  Input `[]` to clear the value of this field. Supports up to 3 phone numbers.
     */
    public $smses;
    /**
     * @var array[] Email address(es) to receive email notifications. Input `[]` to clear the value of this field. Supports up to 3 email addresses.
     */
    public $emails;
    /**
     * @var string By default this field shows the `tracking_number`, but you can customize it as you wish with any info (e.g. the order number).
     */
    public $title;
    /**
     * @var string Customer name of the tracking.
     */
    public $customer_name;
    /**
     * @var string A globally-unique identifier for the order.
     */
    public $order_id;
    /**
     * @var string The URL for the order in your system or store.
     */
    public $order_id_path;
    /**
     * @var array|null Custom fields that accept an object with string field. In order to protect the privacy of your customers, do not include any 
     */
    public $custom_fields;
    /**
     * @var string Text field for the note.Input `""` to clear the value of this field.
     */
    public $note;
    /**
     * @var string The recipient’s language. If you set up AfterShip notifications in different languages, we use this to send the recipient tracking updates in their preferred language. Use an  to specify the language.
     */
    public $language;
    /**
     * @var string The promised delivery date of the order. It uses the formats:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ
     */
    public $order_promised_delivery_date;
    /**
     * @var string|null|string Shipment delivery type- `pickup_at_store`- `pickup_at_courier`- `door_to_door`
     */
    public $delivery_type;
    /**
     * @var string Shipment pickup location for receiver
     */
    public $pickup_location;
    /**
     * @var string Shipment pickup note for receiver
     */
    public $pickup_note;
    /**
     * @var string Unique code of each courier. Provide a single courier.(https://admin.aftership.com/settings/couriers). Get a list of courier slug using 
     */
    public $slug;
    /**
     * @var string Additional field required by some carriers to retrieve the tracking info. The shipper’s carrier account number. Refer to our article on  for more details.
     */
    public $tracking_account_number;
    /**
     * @var string Additional field required by some carriers to retrieve the tracking info. A type of tracking credential required by some carriers. Refer to our article on  for more details.
     */
    public $tracking_key;
    /**
     * @var string Additional field required by some carriers to retrieve the tracking info. The date the shipment was sent, using the format YYYYMMDD. Refer to our article on  for more details.
     */
    public $tracking_ship_date;
    /**
     * @var string A unique, human-readable identifier for the order.
     */
    public $order_number;
    /**
     * @var string Order date in YYYY-MM-DDTHH:mm:ssZ format. e.g. 2021-07-26T11:23:51-05:00
     */
    public $order_date;
    /**
     * @var string The carrier service type for the shipment. If you provide info for this field, AfterShip will not update it with info from the carrier.
     */
    public $shipment_type;
    /**
     * @var string The  for more details.
     */
    public $origin_country_iso3;
    /**
     * @var string The state of the sender’s address. This can help AfterShip with various functions like tracking, carrier auto-detection and auto-correction, calculating an EDD, etc.
     */
    public $origin_state;
    /**
     * @var string The city of the sender’s address. This can help AfterShip with various functions like tracking, carrier auto-detection and auto-correction, calculating an EDD, etc.
     */
    public $origin_city;
    /**
     * @var string The postal of the sender’s address. This can help AfterShip with various functions like tracking, carrier auto-detection and auto-correction, calculating an EDD, etc.
     */
    public $origin_postal_code;
    /**
     * @var string The sender address that the shipment is shipping from. This can help AfterShip with various functions like tracking, carrier auto-detection and auto-correction, calculating an EDD, etc.
     */
    public $origin_raw_location;
    /**
     * @var string The  for more details.
     */
    public $destination_country_iso3;
    /**
     * @var string The state of the recipient’s address. This can help AfterShip with various functions like tracking, carrier auto-detection and auto-correction, calculating an EDD, etc. Also the additional field required by some carriers to retrieve the tracking info. The state/province of the recipient’s address. Refer to our article on  for more details.
     */
    public $destination_state;
    /**
     * @var string The city of the recipient’s address. This can help AfterShip with various functions like tracking, carrier auto-detection and auto-correction, calculating an EDD, etc.
     */
    public $destination_city;
    /**
     * @var string The postal of the recipient’s address. This can help AfterShip with various functions like tracking, carrier auto-detection and auto-correction, calculating an EDD, etc. Also the additional field required by some carriers to retrieve the tracking info. The postal code of the recipient’s address. Refer to our article on  for more details.
     */
    public $destination_postal_code;
    /**
     * @var string The shipping address that the shipment is shipping to. This can help AfterShip with various functions like tracking, carrier auto-detection and auto-correction, calculating an EDD, etc.
     */
    public $destination_raw_location;
    /**
     * @var string (Legacy) Replaced by `origin_country_iso3`. Additional field required by some carriers to retrieve the tracking info. The origin country/region of the shipment. Refer to our article on  for more details.
     */
    public $tracking_origin_country;
    /**
     * @var string (Legacy) Replaced by `destination_country_iso3`. Additional field required by some carriers to retrieve the tracking info. The destination country/region of the shipment. Refer to our article on  for more details.
     */
    public $tracking_destination_country;
    /**
     * @var string (Legacy) Replaced by `destination_postal_code`. Additional field required by some carriers to retrieve the tracking info. The postal code of the recipient’s address. Refer to our article on  for more details.
     */
    public $tracking_postal_code;
    /**
     * @var string (Legacy) Replaced by `destination_state`. Additional field required by some carriers to retrieve the tracking info. The state/province of the recipient’s address. Refer to our article on  for more details.
     */
    public $tracking_state;
    /**
     * @var string The location_id refers to the place where you fulfilled the items.  - If you provide a location_id, the system will automatically use it as the tracking's origin address. However, passing both location_id and any origin address information simultaneously is not allowed.- Please make sure you add your locations .
     */
    public $location_id;
    /**
     * @var string The shipping_method string refers to the chosen method for delivering the package. Merchants typically offer various shipping methods to consumers during the checkout process, such as, Local Delivery, Free Express Worldwide Shipping, etc.
     */
    public $shipping_method;
}
