<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Model\Base;

use Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor;
use Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor;
use Symfony\Component\PropertyInfo\PropertyInfoExtractor;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Normalizer\ArrayDenormalizer;
use Symfony\Component\Serializer\Normalizer\BackedEnumNormalizer;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;
use Symfony\Component\PropertyAccess\PropertyAccess;

class Base
{
    public function toArray(): array
    {
        return json_decode(json_encode($this), true);
    }

    public function toRequestArray(): array
    {
        $normalizers = [new CustomNormalizer()];
        $encoders = [new JsonEncoder()];
        $serializer = new Serializer($normalizers, $encoders);

        // Set the serializer instance for the normalizer
        foreach ($normalizers as $normalizer) {
            if (method_exists($normalizer, 'setSerializer')) {
                $normalizer->setSerializer($serializer);
            }
        }

        $ret = $serializer->normalize($this);
        return $ret;
    }

    public static function fromArray(array $data, $class)
    {
        $encoder = [new JsonEncoder()];
        $extractor = new PropertyInfoExtractor([], [new PhpDocExtractor(), new ReflectionExtractor()]);
        $normalizer = [new BackedEnumNormalizer(), new ArrayDenormalizer(), new ObjectNormalizer(null, null, null, $extractor)];
        $serializer = new Serializer($normalizer, $encoder);
        $obj = $serializer->denormalize($data, $class);

        return $obj;
    }
}
