<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\API;

use Tracking\API\Base\APIBase;
use Tracking\Exception\AfterShipError;
use Tracking\Exception\ErrorCode;
use Tracking\Transport\Http;

class Courier extends APIBase
{
    private $httpClient;

    public function __construct(Http $httpClient)
    {
        $this->httpClient = $httpClient;
    }

    /**
    * @throws AfterShipError
    */
    public function getUserCouriers(
    
    
    
    array $headers = []
    ): \Tracking\API\Courier\GetUserCouriersResponse
    {


        $options = [
            'headers' => $headers,
        
        
        ];
        $resp = $this->httpClient->request('GET', sprintf("/tracking/2024-10/couriers" ), $options);

        return $this->parseSingleResource($resp, \Tracking\API\Courier\GetUserCouriersResponse::class);
    }
    /**
    * @throws AfterShipError
    */
    public function getAllCouriers(
    
    
    
    array $headers = []
    ): \Tracking\API\Courier\GetAllCouriersResponse
    {


        $options = [
            'headers' => $headers,
        
        
        ];
        $resp = $this->httpClient->request('GET', sprintf("/tracking/2024-10/couriers/all" ), $options);

        return $this->parseSingleResource($resp, \Tracking\API\Courier\GetAllCouriersResponse::class);
    }
    /**
    * @throws AfterShipError
    */
    public function detectCourier(
    
     \Tracking\API\Courier\DetectCourierRequest $body, 
    
    array $headers = []
    ): \Tracking\API\Courier\DetectCourierResponse
    {


        $options = [
            'headers' => $headers,
        
        'json' => $body->toRequestArray(),
        ];
        $resp = $this->httpClient->request('POST', sprintf("/tracking/2024-10/couriers/detect" ), $options);

        return $this->parseSingleResource($resp, \Tracking\API\Courier\DetectCourierResponse::class);
    }
}
