<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\API;

use Tracking\API\Base\APIBase;
use Tracking\Exception\AfterShipError;
use Tracking\Exception\ErrorCode;
use Tracking\Transport\Http;
use Tracking\Model\GetCourierConnectionsQuery;

class CourierConnection extends APIBase
{
    private $httpClient;

    public function __construct(Http $httpClient)
    {
        $this->httpClient = $httpClient;
    }

    /**
    * @throws AfterShipError
    */
    public function getCourierConnections(
        ?GetCourierConnectionsQuery $query = null,
        array $headers = []
    ): \Tracking\Model\GetCourierConnectionsResponse {
        $options = [
            'headers' => $headers,
            'query' => $query ? $query->toArray() : [],
        ];
        $httpResp = $this->httpClient->request('GET', sprintf("/tracking/2025-07/courier-connections"), $options);

        return $this->processResponse($httpResp, \Tracking\Model\GetCourierConnectionsResponse::class, \Tracking\Model\GetCourierConnectionsResponseData::class);
    }
    /**
    * @throws AfterShipError
    */
    public function postCourierConnections(
        \Tracking\Model\PostCourierConnectionsRequest $body,
        array $headers = []
    ): \Tracking\Model\PostCourierConnectionsResponse {
        $options = [
            'headers' => $headers,

            'json' => $body->toRequestArray(),
        ];
        $httpResp = $this->httpClient->request('POST', sprintf("/tracking/2025-07/courier-connections"), $options);

        return $this->processResponse($httpResp, \Tracking\Model\PostCourierConnectionsResponse::class, \Tracking\Model\CourierConnection::class);
    }
    /**
    * @throws AfterShipError
    */
    public function getCourierConnectionsById(
        string $id,
        array $headers = []
    ): \Tracking\Model\GetCourierConnectionsByIdResponse {
        if ($id === "") {
            throw ErrorCode::genLocalError(ErrorCode::BAD_REQUEST, "Param 'id' cannot be an empty string");
        }

        $options = [
            'headers' => $headers,
        ];
        $httpResp = $this->httpClient->request('GET', sprintf("/tracking/2025-07/courier-connections/%s", $id), $options);

        return $this->processResponse($httpResp, \Tracking\Model\GetCourierConnectionsByIdResponse::class, \Tracking\Model\CourierConnection::class);
    }
    /**
    * @throws AfterShipError
    */
    public function putCourierConnectionsById(
        string $id,
        \Tracking\Model\PutCourierConnectionsByIdRequest $body,
        array $headers = []
    ): \Tracking\Model\PutCourierConnectionsByIdResponse {
        if ($id === "") {
            throw ErrorCode::genLocalError(ErrorCode::BAD_REQUEST, "Param 'id' cannot be an empty string");
        }

        $options = [
            'headers' => $headers,

            'json' => $body->toRequestArray(),
        ];
        $httpResp = $this->httpClient->request('PATCH', sprintf("/tracking/2025-07/courier-connections/%s", $id), $options);

        return $this->processResponse($httpResp, \Tracking\Model\PutCourierConnectionsByIdResponse::class, \Tracking\Model\CourierConnection::class);
    }
    /**
    * @throws AfterShipError
    */
    public function deleteCourierConnectionsById(
        string $id,
        array $headers = []
    ): \Tracking\Model\DeleteCourierConnectionsByIdResponse {
        if ($id === "") {
            throw ErrorCode::genLocalError(ErrorCode::BAD_REQUEST, "Param 'id' cannot be an empty string");
        }

        $options = [
            'headers' => $headers,
        ];
        $httpResp = $this->httpClient->request('DELETE', sprintf("/tracking/2025-07/courier-connections/%s", $id), $options);

        return $this->processResponse($httpResp, \Tracking\Model\DeleteCourierConnectionsByIdResponse::class, \Tracking\Model\CourierConnection::class);
    }
}
