<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\API;

use Tracking\API\Base\APIBase;
use Tracking\Exception\AfterShipError;
use Tracking\Exception\ErrorCode;
use Tracking\Transport\Http;
use Tracking\Model\GetCouriersQuery;

class Courier extends APIBase
{
    private $httpClient;

    public function __construct(Http $httpClient)
    {
        $this->httpClient = $httpClient;
    }

    /**
    * @throws AfterShipError
    */
    public function getCouriers(
        ?GetCouriersQuery $query = null,
        array $headers = []
    ): \Tracking\Model\GetCouriersResponse {
        $options = [
            'headers' => $headers,
            'query' => $query ? $query->toArray() : [],
        ];
        $httpResp = $this->httpClient->request('GET', sprintf("/tracking/2026-01/couriers"), $options);

        return $this->processResponse($httpResp, \Tracking\Model\GetCouriersResponse::class, \Tracking\Model\GetCouriersResponseData::class);
    }
    /**
    * @throws AfterShipError
    */
    public function detectCourier(
        \Tracking\Model\DetectCourierRequest $body,
        array $headers = []
    ): \Tracking\Model\DetectCourierResponse {
        $options = [
            'headers' => $headers,

            'json' => $body->toRequestArray(),
        ];
        $httpResp = $this->httpClient->request('POST', sprintf("/tracking/2026-01/couriers/detect"), $options);

        return $this->processResponse($httpResp, \Tracking\Model\DetectCourierResponse::class, \Tracking\Model\DetectCourierResponseData::class);
    }
}
