<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\API;

use Tracking\API\Base\APIBase;
use Tracking\Exception\AfterShipError;
use Tracking\Exception\ErrorCode;
use Tracking\Transport\Http;
use Tracking\API\CourierConnection\GetCourierConnectionsQuery;

class CourierConnection extends APIBase
{
    private $httpClient;

    public function __construct(Http $httpClient)
    {
        $this->httpClient = $httpClient;
    }

    /**
    * @throws AfterShipError
    */
    public function getCourierConnectionsById(
        string $id,
        array $headers = []
    ): \Tracking\API\CourierConnection\GetCourierConnectionsByIdResponse {
        if ($id === "") {
            throw ErrorCode::genLocalError(ErrorCode::INVALID_REQUEST, "Param 'id' cannot be an empty string");
        }

        $options = [
            'headers' => $headers,
        ];
        $resp = $this->httpClient->request('GET', sprintf("/tracking/2025-07/courier-connections/%s", $id), $options);

        return $this->parseSingleResource($resp, \Tracking\API\CourierConnection\GetCourierConnectionsByIdResponse::class);
    }
    /**
    * @throws AfterShipError
    */
    public function getCourierConnections(
        GetCourierConnectionsQuery $query = null,
        array $headers = []
    ): \Tracking\API\CourierConnection\GetCourierConnectionsResponse {
        $options = [
            'headers' => $headers,
            'query' => $query ? $query->toArray() : [],
        ];
        $resp = $this->httpClient->request('GET', sprintf("/tracking/2025-07/courier-connections"), $options);

        return $this->parseSingleResource($resp, \Tracking\API\CourierConnection\GetCourierConnectionsResponse::class);
    }
    /**
    * @throws AfterShipError
    */
    public function postCourierConnections(
        \Tracking\API\CourierConnection\PostCourierConnectionsRequest $body,
        array $headers = []
    ): \Tracking\API\CourierConnection\PostCourierConnectionsResponse {
        $options = [
            'headers' => $headers,

            'json' => $body->toRequestArray(),
        ];
        $resp = $this->httpClient->request('POST', sprintf("/tracking/2025-07/courier-connections"), $options);

        return $this->parseSingleResource($resp, \Tracking\API\CourierConnection\PostCourierConnectionsResponse::class);
    }
    /**
    * @throws AfterShipError
    */
    public function putCourierConnectionsById(
        string $id,
        \Tracking\API\CourierConnection\PutCourierConnectionsByIdRequest $body,
        array $headers = []
    ): \Tracking\API\CourierConnection\PutCourierConnectionsByIdResponse {
        if ($id === "") {
            throw ErrorCode::genLocalError(ErrorCode::INVALID_REQUEST, "Param 'id' cannot be an empty string");
        }

        $options = [
            'headers' => $headers,

            'json' => $body->toRequestArray(),
        ];
        $resp = $this->httpClient->request('PATCH', sprintf("/tracking/2025-07/courier-connections/%s", $id), $options);

        return $this->parseSingleResource($resp, \Tracking\API\CourierConnection\PutCourierConnectionsByIdResponse::class);
    }
    /**
    * @throws AfterShipError
    */
    public function deleteCourierConnectionsById(
        string $id,
        array $headers = []
    ): \Tracking\API\CourierConnection\DeleteCourierConnectionsByIdResponse {
        if ($id === "") {
            throw ErrorCode::genLocalError(ErrorCode::INVALID_REQUEST, "Param 'id' cannot be an empty string");
        }

        $options = [
            'headers' => $headers,
        ];
        $resp = $this->httpClient->request('DELETE', sprintf("/tracking/2025-07/courier-connections/%s", $id), $options);

        return $this->parseSingleResource($resp, \Tracking\API\CourierConnection\DeleteCourierConnectionsByIdResponse::class);
    }
}
