<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\API;

use Tracking\API\Base\APIBase;
use Tracking\Exception\AfterShipError;
use Tracking\Exception\ErrorCode;
use Tracking\Transport\Http;

class EstimatedDeliveryDate extends APIBase
{
    private $httpClient;

    public function __construct(Http $httpClient)
    {
        $this->httpClient = $httpClient;
    }

    /**
    * @throws AfterShipError
    */
    public function predict(
        \Tracking\Model\EstimatedDeliveryDateRequest $body,
        array $headers = []
    ): \Tracking\Model\PredictResponse {
        $options = [
            'headers' => $headers,

            'json' => $body->toRequestArray(),
        ];
        $httpResp = $this->httpClient->request('POST', sprintf("/tracking/2026-07/estimated-delivery-date/predict"), $options);

        return $this->processResponse($httpResp, \Tracking\Model\PredictResponse::class, \Tracking\Model\EstimatedDeliveryDateResponse::class);
    }
    /**
    * @throws AfterShipError
    */
    public function predictBatch(
        \Tracking\Model\PredictBatchRequest $body,
        array $headers = []
    ): \Tracking\Model\PredictBatchResponse {
        $options = [
            'headers' => $headers,

            'json' => $body->toRequestArray(),
        ];
        $httpResp = $this->httpClient->request('POST', sprintf("/tracking/2026-07/estimated-delivery-date/predict-batch"), $options);

        return $this->processResponse($httpResp, \Tracking\Model\PredictBatchResponse::class, \Tracking\Model\PredictBatchResponseData::class);
    }
}
