<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\API;

use Tracking\API\Base\APIBase;
use Tracking\Exception\AfterShipError;
use Tracking\Exception\ErrorCode;
use Tracking\Transport\Http;

class EstimatedDeliveryDate extends APIBase
{
    private $httpClient;

    public function __construct(Http $httpClient)
    {
        $this->httpClient = $httpClient;
    }

    /**
    * @throws AfterShipError
    */
    public function predictBatch(
    
     \Tracking\API\EstimatedDeliveryDate\PredictBatchRequest $body, 
    
    array $headers = []
    ): \Tracking\API\EstimatedDeliveryDate\PredictBatchResponse
    {


        $options = [
            'headers' => $headers,
        
        'json' => $body->toRequestArray(),
        ];
        $resp = $this->httpClient->request('POST', sprintf("/tracking/2024-10/estimated-delivery-date/predict-batch" ), $options);

        return $this->parseSingleResource($resp, \Tracking\API\EstimatedDeliveryDate\PredictBatchResponse::class);
    }
}
