<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\API;

use Tracking\API\Base\APIBase;
use Tracking\Exception\AfterShipError;
use Tracking\Exception\ErrorCode;
use Tracking\Transport\Http;
use Tracking\API\Notification\DeleteNotificationBySlugTrackingNumberQuery;
use Tracking\API\Notification\GetNotificationBySlugTrackingNumberQuery;
use Tracking\API\Notification\AddNotificationBySlugTrackingNumberQuery;

class Notification extends APIBase
{
    private $httpClient;

    public function __construct(Http $httpClient)
    {
        $this->httpClient = $httpClient;
    }

    /**
    * @throws AfterShipError
    */
    public function addNotificationByTrackingId(
        string $tracking_id,
        \Tracking\Model\NotificationRequestV1 $body,
        array $headers = []
    ): \Tracking\Model\Notification {
        if ($tracking_id === "") {
            throw ErrorCode::genLocalError(ErrorCode::INVALID_REQUEST, "Param 'tracking_id' cannot be an empty string");
        }

        $options = [
            'headers' => $headers,

            'json' => ['notification' => $body->toRequestArray()],
        ];
        $resp = $this->httpClient->request('POST', sprintf("/tracking/2024-04/notifications/%s/add", $tracking_id), $options);
        $result = $this->parseSingleResource($resp, 'notification', \Tracking\Model\Notification::class);
        return $result;
    }
    /**
    * @throws AfterShipError
    */
    public function deleteNotificationBySlugTrackingNumber(
        string $slug,
        string $tracking_number,
        \Tracking\Model\NotificationRequestV1 $body,
        DeleteNotificationBySlugTrackingNumberQuery $query = null,
        array $headers = []
    ): \Tracking\Model\Notification {
        if ($slug === "") {
            throw ErrorCode::genLocalError(ErrorCode::INVALID_REQUEST, "Param 'slug' cannot be an empty string");
        }
        if ($tracking_number === "") {
            throw ErrorCode::genLocalError(ErrorCode::INVALID_REQUEST, "Param 'tracking_number' cannot be an empty string");
        }

        $options = [
            'headers' => $headers,
            'query' => $query ? $query->toArray() : [],
            'json' => ['notification' => $body->toRequestArray()],
        ];
        $resp = $this->httpClient->request('POST', sprintf("/tracking/2024-04/notifications/%s/%s/remove", $slug, $tracking_number), $options);
        $result = $this->parseSingleResource($resp, 'notification', \Tracking\Model\Notification::class);
        return $result;
    }
    /**
    * @throws AfterShipError
    */
    public function getNotificationByTrackingId(
        string $tracking_id,
        array $headers = []
    ): \Tracking\Model\Notification {
        if ($tracking_id === "") {
            throw ErrorCode::genLocalError(ErrorCode::INVALID_REQUEST, "Param 'tracking_id' cannot be an empty string");
        }

        $options = [
            'headers' => $headers,
        ];
        $resp = $this->httpClient->request('GET', sprintf("/tracking/2024-04/notifications/%s", $tracking_id), $options);
        $result = $this->parseSingleResource($resp, 'notification', \Tracking\Model\Notification::class);
        return $result;
    }
    /**
    * @throws AfterShipError
    */
    public function getNotificationBySlugTrackingNumber(
        string $slug,
        string $tracking_number,
        GetNotificationBySlugTrackingNumberQuery $query = null,
        array $headers = []
    ): \Tracking\Model\Notification {
        if ($slug === "") {
            throw ErrorCode::genLocalError(ErrorCode::INVALID_REQUEST, "Param 'slug' cannot be an empty string");
        }
        if ($tracking_number === "") {
            throw ErrorCode::genLocalError(ErrorCode::INVALID_REQUEST, "Param 'tracking_number' cannot be an empty string");
        }

        $options = [
            'headers' => $headers,
            'query' => $query ? $query->toArray() : [],
        ];
        $resp = $this->httpClient->request('GET', sprintf("/tracking/2024-04/notifications/%s/%s", $slug, $tracking_number), $options);
        $result = $this->parseSingleResource($resp, 'notification', \Tracking\Model\Notification::class);
        return $result;
    }
    /**
    * @throws AfterShipError
    */
    public function addNotificationBySlugTrackingNumber(
        string $slug,
        string $tracking_number,
        \Tracking\Model\NotificationRequestV1 $body,
        AddNotificationBySlugTrackingNumberQuery $query = null,
        array $headers = []
    ): \Tracking\Model\Notification {
        if ($slug === "") {
            throw ErrorCode::genLocalError(ErrorCode::INVALID_REQUEST, "Param 'slug' cannot be an empty string");
        }
        if ($tracking_number === "") {
            throw ErrorCode::genLocalError(ErrorCode::INVALID_REQUEST, "Param 'tracking_number' cannot be an empty string");
        }

        $options = [
            'headers' => $headers,
            'query' => $query ? $query->toArray() : [],
            'json' => ['notification' => $body->toRequestArray()],
        ];
        $resp = $this->httpClient->request('POST', sprintf("/tracking/2024-04/notifications/%s/%s/add", $slug, $tracking_number), $options);
        $result = $this->parseSingleResource($resp, 'notification', \Tracking\Model\Notification::class);
        return $result;
    }
    /**
    * @throws AfterShipError
    */
    public function deleteNotificationByTrackingId(
        string $tracking_id,
        \Tracking\Model\NotificationRequestV1 $body,
        array $headers = []
    ): \Tracking\Model\Notification {
        if ($tracking_id === "") {
            throw ErrorCode::genLocalError(ErrorCode::INVALID_REQUEST, "Param 'tracking_id' cannot be an empty string");
        }

        $options = [
            'headers' => $headers,

            'json' => ['notification' => $body->toRequestArray()],
        ];
        $resp = $this->httpClient->request('POST', sprintf("/tracking/2024-04/notifications/%s/remove", $tracking_id), $options);
        $result = $this->parseSingleResource($resp, 'notification', \Tracking\Model\Notification::class);
        return $result;
    }
}
