<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\API;

use Tracking\API\Base\APIBase;
use Tracking\Exception\AfterShipError;
use Tracking\Exception\ErrorCode;
use Tracking\Transport\Http;
use Tracking\Model\GetTrackingsQuery;
use Tracking\Model\GetTrackingByIdQuery;

class Tracking extends APIBase
{
    private $httpClient;

    public function __construct(Http $httpClient)
    {
        $this->httpClient = $httpClient;
    }

    /**
    * @throws AfterShipError
    */
    public function getTrackings(
        ?GetTrackingsQuery $query = null,
        array $headers = []
    ): \Tracking\Model\GetTrackingsResponse {
        $options = [
            'headers' => $headers,
            'query' => $query ? $query->toArray() : [],
        ];
        $httpResp = $this->httpClient->request('GET', sprintf("/tracking/2026-07/trackings"), $options);

        return $this->processResponse($httpResp, \Tracking\Model\GetTrackingsResponse::class, \Tracking\Model\GetTrackingsResponseData::class);
    }
    /**
    * @throws AfterShipError
    */
    public function createTracking(
        \Tracking\Model\CreateTrackingRequest $body,
        array $headers = []
    ): \Tracking\Model\CreateTrackingResponse {
        $options = [
            'headers' => $headers,

            'json' => $body->toRequestArray(),
        ];
        $httpResp = $this->httpClient->request('POST', sprintf("/tracking/2026-07/trackings"), $options);

        return $this->processResponse($httpResp, \Tracking\Model\CreateTrackingResponse::class, \Tracking\Model\Tracking::class);
    }
    /**
    * @throws AfterShipError
    */
    public function getTrackingById(
        string $id,
        ?GetTrackingByIdQuery $query = null,
        array $headers = []
    ): \Tracking\Model\GetTrackingByIdResponse {
        if ($id === "") {
            throw ErrorCode::genLocalError(ErrorCode::BAD_REQUEST, "Param 'id' cannot be an empty string");
        }

        $options = [
            'headers' => $headers,
            'query' => $query ? $query->toArray() : [],
        ];
        $httpResp = $this->httpClient->request('GET', sprintf("/tracking/2026-07/trackings/%s", $id), $options);

        return $this->processResponse($httpResp, \Tracking\Model\GetTrackingByIdResponse::class, \Tracking\Model\Tracking::class);
    }
    /**
    * @throws AfterShipError
    */
    public function updateTrackingById(
        string $id,
        \Tracking\Model\UpdateTrackingByIdRequest $body,
        array $headers = []
    ): \Tracking\Model\UpdateTrackingByIdResponse {
        if ($id === "") {
            throw ErrorCode::genLocalError(ErrorCode::BAD_REQUEST, "Param 'id' cannot be an empty string");
        }

        $options = [
            'headers' => $headers,

            'json' => $body->toRequestArray(),
        ];
        $httpResp = $this->httpClient->request('PUT', sprintf("/tracking/2026-07/trackings/%s", $id), $options);

        return $this->processResponse($httpResp, \Tracking\Model\UpdateTrackingByIdResponse::class, \Tracking\Model\Tracking::class);
    }
    /**
    * @throws AfterShipError
    */
    public function deleteTrackingById(
        string $id,
        array $headers = []
    ): \Tracking\Model\DeleteTrackingByIdResponse {
        if ($id === "") {
            throw ErrorCode::genLocalError(ErrorCode::BAD_REQUEST, "Param 'id' cannot be an empty string");
        }

        $options = [
            'headers' => $headers,
        ];
        $httpResp = $this->httpClient->request('DELETE', sprintf("/tracking/2026-07/trackings/%s", $id), $options);

        return $this->processResponse($httpResp, \Tracking\Model\DeleteTrackingByIdResponse::class, \Tracking\Model\Tracking::class);
    }
    /**
    * @throws AfterShipError
    */
    public function retrackTrackingById(
        string $id,
        array $headers = []
    ): \Tracking\Model\RetrackTrackingByIdResponse {
        if ($id === "") {
            throw ErrorCode::genLocalError(ErrorCode::BAD_REQUEST, "Param 'id' cannot be an empty string");
        }

        $options = [
            'headers' => $headers,
        ];
        $httpResp = $this->httpClient->request('POST', sprintf("/tracking/2026-07/trackings/%s/retrack", $id), $options);

        return $this->processResponse($httpResp, \Tracking\Model\RetrackTrackingByIdResponse::class, \Tracking\Model\Tracking::class);
    }
    /**
    * @throws AfterShipError
    */
    public function markTrackingCompletedById(
        string $id,
        \Tracking\Model\MarkTrackingCompletedByIdRequest $body,
        array $headers = []
    ): \Tracking\Model\MarkTrackingCompletedByIdResponse {
        if ($id === "") {
            throw ErrorCode::genLocalError(ErrorCode::BAD_REQUEST, "Param 'id' cannot be an empty string");
        }

        $options = [
            'headers' => $headers,

            'json' => $body->toRequestArray(),
        ];
        $httpResp = $this->httpClient->request('POST', sprintf("/tracking/2026-07/trackings/%s/mark-as-completed", $id), $options);

        return $this->processResponse($httpResp, \Tracking\Model\MarkTrackingCompletedByIdResponse::class, \Tracking\Model\Tracking::class);
    }
}
