<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\API\Notification;

use Tracking\Model\Base\Base;

class DeleteNotificationByTrackingIdRequest extends Base
{
    /**
     * @var \Tracking\Model\NotificationRequestV1 Notification request object
     */
    public $notification;
}
