<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\API\LastCheckpoint;

class GetCheckpointByTrackingIdQuery extends \Tracking\API\Base\QueryBase
{
    /**
     * @var string|null List of fields to include in the response. Use comma for multiple values. Fields to include: `slug`, `created_at`, `checkpoint_time`, `city`, `coordinates`, `country_iso3`, `country_name`, `message`, `state`, `tag`, `zip`
     */
    public $fields;
    /**
     * @var string|null Support Chinese to English translation for `china-ems` and `china-post` only
     */
    public $lang;

    public function setFields(string $fields): GetCheckpointByTrackingIdQuery
    {
        $this->fields = $fields;
        return $this;
    }
    public function setLang(string $lang): GetCheckpointByTrackingIdQuery
    {
        $this->lang = $lang;
        return $this;
    }
}
