<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\API\LastCheckpoint;

class GetCheckpointBySlugTrackingNumberQuery extends \Tracking\API\Base\QueryBase
{
    /**
     * @var string|null List of fields to include in the response. Use comma for multiple values. Fields to include: `slug`, `created_at`, `checkpoint_time`, `city`, `coordinates`, `country_iso3`, `country_name`, `message`, `state`, `tag`, `zip`
     */
    public $fields;
    /**
     * @var string|null Support Chinese to English translation for `china-ems` and `china-post` only
     */
    public $lang;
    /**
     * @var string|null Additional field required by some carriers to retrieve the tracking info. The shipper’s carrier account number. Refer to our article on  for more details.
     */
    public $tracking_account_number;
    /**
     * @var string|null Additional field required by some carriers to retrieve the tracking info. The origin country/region of the shipment. Refer to our article on  for more details.
     */
    public $tracking_origin_country;
    /**
     * @var string|null Additional field required by some carriers to retrieve the tracking info. The destination country/region of the shipment. Refer to our article on  for more details.
     */
    public $tracking_destination_country;
    /**
     * @var string|null Additional field required by some carriers to retrieve the tracking info. A type of tracking credential required by some carriers. Refer to our article on  for more details.
     */
    public $tracking_key;
    /**
     * @var string|null Additional field required by some carriers to retrieve the tracking info. The postal code of the recipient’s address. Refer to our article on  for more details.
     */
    public $tracking_postal_code;
    /**
     * @var string|null Additional field required by some carriers to retrieve the tracking info. The date the shipment was sent, using the format YYYYMMDD. Refer to our article on  for more details.
     */
    public $tracking_ship_date;
    /**
     * @var string|null Additional field required by some carriers to retrieve the tracking info. The state/province of the recipient’s address. Refer to our article on  for more details.
     */
    public $tracking_state;

    public function setFields(string $fields): GetCheckpointBySlugTrackingNumberQuery
    {
        $this->fields = $fields;
        return $this;
    }
    public function setLang(string $lang): GetCheckpointBySlugTrackingNumberQuery
    {
        $this->lang = $lang;
        return $this;
    }
    public function setTrackingAccountNumber(string $tracking_account_number): GetCheckpointBySlugTrackingNumberQuery
    {
        $this->tracking_account_number = $tracking_account_number;
        return $this;
    }
    public function setTrackingOriginCountry(string $tracking_origin_country): GetCheckpointBySlugTrackingNumberQuery
    {
        $this->tracking_origin_country = $tracking_origin_country;
        return $this;
    }
    public function setTrackingDestinationCountry(string $tracking_destination_country): GetCheckpointBySlugTrackingNumberQuery
    {
        $this->tracking_destination_country = $tracking_destination_country;
        return $this;
    }
    public function setTrackingKey(string $tracking_key): GetCheckpointBySlugTrackingNumberQuery
    {
        $this->tracking_key = $tracking_key;
        return $this;
    }
    public function setTrackingPostalCode(string $tracking_postal_code): GetCheckpointBySlugTrackingNumberQuery
    {
        $this->tracking_postal_code = $tracking_postal_code;
        return $this;
    }
    public function setTrackingShipDate(string $tracking_ship_date): GetCheckpointBySlugTrackingNumberQuery
    {
        $this->tracking_ship_date = $tracking_ship_date;
        return $this;
    }
    public function setTrackingState(string $tracking_state): GetCheckpointBySlugTrackingNumberQuery
    {
        $this->tracking_state = $tracking_state;
        return $this;
    }
}
