<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\API\LastCheckpoint;

use Tracking\Model\Base\Base;

class GetCheckpointByTrackingIdResponse extends Base
{
    /**
     * @var string Tracking id
     */
    public $id;
    /**
     * @var string Tracking number.
     */
    public $tracking_number;
    /**
     * @var string Unique code of courier.
     */
    public $slug;
    /**
     * @var string|null|\Tracking\Model\TagV1 Current status of tracking. (
     */
    public $tag;
    /**
     * @var string Current subtag of tracking. (
     */
    public $subtag;
    /**
     * @var string Normalized tracking message. (
     */
    public $subtag_message;
    /**
     * @var \Tracking\Model\Checkpoint Object describes checkpoint information.
     */
    public $checkpoint;
}
