<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Exception;

class ErrorCode
{
    final const INVALID_API_KEY = 'INVALID_API_KEY';
    final const INVALID_OPTION = 'INVALID_OPTION';
    final const BAD_REQUEST = 'BAD_REQUEST';
    final const RATE_LIMIT_EXCEED = 'RATE_LIMIT_EXCEED';
    final const TIMED_OUT = 'TIMED_OUT';
    final const UNKNOWN_ERROR = 'UNKNOWN_ERROR';
    final const INVALID_REQUEST = 'INVALID_REQUEST';
    final const INVALID_JSON = 'INVALID_JSON';
    final const TRACKING_ALREADY_EXIST = 'TRACKING_ALREADY_EXIST';
    final const TRACKING_DOES_NOT_EXIST = 'TRACKING_DOES_NOT_EXIST';
    final const TRACKING_NUMBER_INVALID = 'TRACKING_NUMBER_INVALID';
    final const TRACKING_REQUIRED = 'TRACKING_REQUIRED';
    final const TRACKING_NUMBER_REQUIRED = 'TRACKING_NUMBER_REQUIRED';
    final const VALUE_INVALID = 'VALUE_INVALID';
    final const VALUE_REQUIRED = 'VALUE_REQUIRED';
    final const SLUG_INVALID = 'SLUG_INVALID';
    final const MISSING_OR_INVALID_REQUIRED_FIELD = 'MISSING_OR_INVALID_REQUIRED_FIELD';
    final const BAD_COURIER = 'BAD_COURIER';
    final const INACTIVE_RETRACK_NOT_ALLOWED = 'INACTIVE_RETRACK_NOT_ALLOWED';
    final const NOTIFICATION_REQUIRED = 'NOTIFICATION_REQUIRED';
    final const ID_INVALID = 'ID_INVALID';
    final const RETRACK_ONCE_ALLOWED = 'RETRACK_ONCE_ALLOWED';
    final const TRACKING_NUMBER_FORMAT_INVALID = 'TRACKING_NUMBER_FORMAT_INVALID';
    final const API_KEY_INVALID = 'API_KEY_INVALID';
    final const REQUEST_NOT_ALLOWED = 'REQUEST_NOT_ALLOWED';
    final const NOT_FOUND = 'NOT_FOUND';
    final const TOO_MANY_REQUEST = 'TOO_MANY_REQUEST';
    final const INTERNAL_ERROR = 'INTERNAL_ERROR';

    private static $errorMap = [
        400 => self::INVALID_REQUEST,
        4001 => self::INVALID_JSON,
        4003 => self::TRACKING_ALREADY_EXIST,
        4004 => self::TRACKING_DOES_NOT_EXIST,
        4005 => self::TRACKING_NUMBER_INVALID,
        4006 => self::TRACKING_REQUIRED,
        4007 => self::TRACKING_NUMBER_REQUIRED,
        4008 => self::VALUE_INVALID,
        4009 => self::VALUE_REQUIRED,
        4010 => self::SLUG_INVALID,
        4011 => self::MISSING_OR_INVALID_REQUIRED_FIELD,
        4012 => self::BAD_COURIER,
        4013 => self::INACTIVE_RETRACK_NOT_ALLOWED,
        4014 => self::NOTIFICATION_REQUIRED,
        4015 => self::ID_INVALID,
        4016 => self::RETRACK_ONCE_ALLOWED,
        4017 => self::TRACKING_NUMBER_FORMAT_INVALID,
        401 => self::API_KEY_INVALID,
        403 => self::REQUEST_NOT_ALLOWED,
        404 => self::NOT_FOUND,
        429 => self::TOO_MANY_REQUEST,
        500 => self::INTERNAL_ERROR,
        502 => self::INTERNAL_ERROR,
        503 => self::INTERNAL_ERROR,
        504 => self::INTERNAL_ERROR,
    ];

    public static function genRemoteError($statusCode, $metaCode, $responseBody = null, $message = null, $responseHeader = null): AfterShipError
    {
        $errorCode = self::locateErrorCode($metaCode, $statusCode);
        return self::genError($errorCode, $statusCode, $metaCode, $responseBody, $message, $responseHeader);
    }

    public static function genLocalError($errorCode, $message = null): AfterShipError
    {
        return self::genError($errorCode, null, null, null, $message);
    }

    public static function genError($errorCode, $statusCode, $metaCode, $responseBody = null, $message = null, $responseHeader = null): AfterShipError
    {
        if (empty($message)) {
            $message = "Unknown error";
        }
        return new AfterShipError($message, $errorCode, $statusCode, $metaCode, $responseBody, $responseHeader);
    }

    private static function locateErrorCode($metaCode, $statusCode): string
    {
        if (isset(self::$errorMap[$metaCode])) {
            return self::$errorMap[$metaCode];
        }

        if ($statusCode >= 500) {
            return self::UNKNOWN_ERROR;
        }
        if ($statusCode >= 400) {
            return self::BAD_REQUEST;
        }
        return self::UNKNOWN_ERROR;
    }
}
