<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\Transport;

use phpseclib3\Crypt\RSA;

class Encryption
{
    /**
     * Calculate the digest of data with RSA_SIGN_PSS_2048_SHA256 algorithm.
     * @param $data string The data to be encrypted.
     * @param $privateKey string The private key
     * @param $password string The private key password
     * @return string the encrypted result with base64 encode
     */
    public static function rsaPSSSha256Encrypt(string $data, string $privateKey, string $password = ''): string
    {
        $key = RSA::loadPrivateKey($privateKey, $password)
            ->withHash("sha256")
            ->withPadding(RSA::SIGNATURE_PSS)
            ->sign($data);
        return base64_encode($key);
    }

    /**
     * Calculate the hash of data with hmac-sha256 algorithm.
     * @param $data string The data to be encrypted.
     * @param $key string The private key
     * @return string the encrypted result with base64 encode
     */
    public static function hmacSha256Encrypt(string $data, string $key): string
    {
        return base64_encode(hash_hmac('sha256', $data, $key, true));
    }
}
