<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\API\EstimatedDeliveryDate;

use Tracking\Model\Base\Base;

class PredictBatchRequest extends Base
{
    /**
     * @var \Tracking\Model\EstimatedDeliveryDateRequest[] 
     */
    public $estimated_delivery_dates;
}
