<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\API\EstimatedDeliveryDate;

use Tracking\Model\Base\Base;

class WeightPredictResponse extends Base
{
    /**
     * @var string The weight unit of the package.
     */
    public $unit;
    /**
     * @var int|float The weight of the shipment.
     */
    public $value;
}
