<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\API\CourierConnection;

use Tracking\Model\Base\Base;

class GetCourierConnectionsResponse extends Base
{
    /**
     * @var PaginationGetCourierConnectionsResponse
     */
    public $pagination;
    /**
     * @var \Tracking\Model\CourierConnection[]
     */
    public $courier_connections;
}
