<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\API\CourierConnection;

class GetCourierConnectionsQuery extends \Tracking\API\Base\QueryBase
{
    /**
     * @var string|null Unique courier code.(Example: dhl-api)
     */
    public $courier_slug;
    /**
     * @var string|null A string representing the cursor value for the current page of results.
     */
    public $cursor;
    /**
     * @var string|null Number of courier connections each page contain. (Default: 100, Max: 200)
     */
    public $limit;

    public function setCourierSlug(string $courier_slug): GetCourierConnectionsQuery
    {
        $this->courier_slug = $courier_slug;
        return $this;
    }
    public function setCursor(string $cursor): GetCourierConnectionsQuery
    {
        $this->cursor = $cursor;
        return $this;
    }
    public function setLimit(string $limit): GetCourierConnectionsQuery
    {
        $this->limit = $limit;
        return $this;
    }
}
