<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\API\CourierConnection;

use Tracking\Model\Base\Base;

class PostCourierConnectionsRequest extends Base
{
    /**
     * @var string Unique code of courier. Get the slugs from .
     */
    public $courier_slug;
    /**
     * @var array|null It refers to the authentication details required for each specific carrier details required for each specific carrier (such as API keys, username, password, etc.) that the user must provide to establish a carrier connection. The content varies by carrier.
     */
    public $credentials;
}
