<?php
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace Tracking\API\Base;

use Tracking\Exception\ErrorCode;
use Psr\Http\Message\ResponseInterface;

class APIBase
{
    protected function parseSingleResource(ResponseInterface $resp, $modelClass)
    {
        $body = $resp->getBody()->getContents();
        $statusCode = $resp->getStatusCode();
        $response = json_decode($body, true);

        if ($statusCode < 200 || $statusCode > 299) {
            throw ErrorCode::genRemoteError($statusCode, $response['meta']['code'] ?? null, $body, $response['meta']['message'] ?? null);
        }

        return $modelClass::fromArray($response['data'], $modelClass);
    }
}
